### ISSUE TITLE
cannot exit screen: 'Failed, Phone not connected'.

### ISSUE THREAD

**Issue by Floris3** [hatl/hasscontrol#31] opened 2023-07-20 12:15 UTC
When opening HassControll via the glance, and the device is not connected we see the error 'Failed, Phone not connected'.
It is not possible to leave this errorscreen when the phone remains unconnected. The back button brings the user back to the entities where upon loading the app notices the phone is not connected, showing the errorscreen and a loop is born.

Tested on Forerunner 255S.

**Comment by hatl** [comment] 2023-08-29 19:03
unfortunately, I can't reproduce the issue.
is this still happening?

**Comment by Floris3** [comment] 2023-09-05 12:32
Yes, it is still happening. I tested by disabling bluetooth on mobile,
navigating on my Forerunner 255S music to the hasscontrol app where it
immediately sais 'Failed, Phone not connected'. The Back button, as well as
all other buttons cannot get me out of that screen. However, after waiting
for [what seems like] 120 seconds, the app automatically exits.

**Comment by xstrex** [comment] 2024-02-04 06:10
Came here to report this, issue still exists, fenix 7X pro sapphire, latest os, and app release.

**Comment by hatl** [comment] 2024-04-13 20:03
fixed in v1.2.0 (verified in simulator)

**Closed by hatl** 2024-04-13 20:03 UTC
